# Generated by Django 4.2.2 on 2023-06-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0002_group_members_group_mods"),
        ("users", "0003_alter_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="Content"
                    ),
                ),
                ("image", models.ImageField(upload_to=None, verbose_name="Image")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "posted_At",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.group"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
