# Generated by Django 4.2.2 on 2023-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_image"),
        ("posts", "0002_post_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="posted_At",
            new_name="posted_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to=None, verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(related_name="likes", to="users.user"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="title"
            ),
        ),
    ]
