# Generated by Django 4.2.2 on 2023-07-23 14:44

from django.db import migrations, models
import users.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_column="username",
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="Name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, verbose_name="Phone"
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, verbose_name="Bio"
                    ),
                ),
                ("image", models.ImageField(upload_to=None, verbose_name="Image")),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="State"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="Country"
                    ),
                ),
            ],
            options={"abstract": False},
            managers=[("objects", users.manager.UserManager())],
        )
    ]
