# Generated by Django 4.2.2 on 2023-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="images", verbose_name="Image"),
        ),
    ]
