# Generated by Django 4.2.2 on 2023-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, db_index=True, upload_to="images", verbose_name="Image"
            ),
        ),
    ]
