# Generated by Django 4.2.2 on 2023-07-12 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_score"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Score",
            new_name="UserLoginSms",
        ),
    ]
