# Generated by Django 4.2.2 on 2023-07-23 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("users", "0005_remove_user_username")]

    operations = [migrations.RemoveField(model_name="user", name="is_superuser")]
