# Generated by Django 4.2.2 on 2023-07-12 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_score_userloginsms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLoginSms",
        ),
    ]
