# Generated by Django 4.2.2 on 2023-07-12 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_loginsms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginSms",
        ),
    ]
