# Generated by Django 4.2.3 on 2023-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_user_is_active_user_is_superuser")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
