# Generated by Django 4.2.2 on 2023-06-27 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commented_at",
            new_name="commented_At",
        ),
    ]
