# Generated by Django 4.2.2 on 2023-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_image"),
        ("comments", "0002_rename_commented_at_comment_commented_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commented_At",
            new_name="commented_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(related_name="like", to="users.user"),
        ),
    ]
