# Generated by Django 4.2.2 on 2023-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_image"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(related_name="members", to="users.user"),
        ),
        migrations.AddField(
            model_name="group",
            name="mods",
            field=models.ManyToManyField(related_name="mods", to="users.user"),
        ),
    ]
