# Generated by Django 4.2.2 on 2023-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_group_members_group_mods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="name"
            ),
        ),
    ]
